import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-6 gap-4 h-screen">
          <div className="col-start-1 col-end-7 "><Header /></div>
          <div className="col-start-1 col-end-7 ">
            <div className="max-w-screen-xl mx-auto">
              {children}
            </div>
          </div>
          <div className="col-start-1 col-end-7 flex items-end"><Footer /></div>
        </div>
      </body>
    </html>
  );
}
